After preprocessing the message ids are stored in two files 'easyham.csv'(non phishing message id) and 'phishing.csv'

In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('easy_ham.csv')
rhs_data=df['RHS'] #0nly RHS containing domain name is needed

In [ ]:
import nltk, re, string, collections
from nltk.util import ngrams # function for making ngrams
i=0
list1=[]
str=''
while(i<len(rhs_data)):
    str=str+ ' '+ rhs_data[i]
    esBigrams = ngrams(i, 2)  #Bigram of RHS is generated
    #list1.append(list(esBigrams))
    i=i+1

In [133]:
list1

[[('h', 'o'),
  ('o', 't'),
  ('t', 'm'),
  ('m', 'a'),
  ('a', 'i'),
  ('i', 'l'),
  ('l', '.'),
  ('.', 'c'),
  ('c', 'o'),
  ('o', 'm')],
 [('m', 'a'),
  ('a', 'i'),
  ('i', 'l'),
  ('l', '2'),
  ('2', '.'),
  ('.', 'd'),
  ('d', 'o'),
  ('o', 'm'),
  ('m', 'a'),
  ('a', 'i'),
  ('i', 'n'),
  ('n', '.'),
  ('.', 'c'),
  ('c', 'o'),
  ('o', 'm')],
 [('r', 'e'),
  ('e', 'p'),
  ('p', 'l'),
  ('l', 'y'),
  ('y', '3'),
  ('3', '.'),
  ('.', 'e'),
  ('e', 'b'),
  ('b', 'a'),
  ('a', 'y'),
  ('y', '.'),
  ('.', 'c'),
  ('c', 'o'),
  ('o', 'm')],
 [('m', 'y'),
  ('y', 's'),
  ('s', 'e'),
  ('e', 'l'),
  ('l', 'v'),
  ('v', 'e'),
  ('e', 's')],
 [('g', 'o'),
  ('o', 'l'),
  ('l', 'd'),
  ('d', 'e'),
  ('e', 'n'),
  ('n', 'm'),
  ('m', 'a'),
  ('a', 'i'),
  ('i', 'l'),
  ('l', '.'),
  ('.', 'r'),
  ('r', 'u')],
 [('c', 'h'),
  ('h', 'a'),
  ('a', 'r'),
  ('r', 't'),
  ('t', 'e'),
  ('e', 'r'),
  ('r', '.'),
  ('.', 'n'),
  ('n', 'e'),
  ('e', 't')],
 [('m', 'y'),
  ('y', 's'),
  ('s', 'e'),


In [67]:
import numpy as np
import pandas as pd
df=pd.read_csv('phishing.csv')
rhs_data=df['RHS']

In [68]:
import nltk
from nltk.util import ngrams
from nltk.collocations import BigramCollocationFinder
from nltk.metrics import BigramAssocMeasures
import re, string, collections
from nltk.util import ngrams # function for making ngrams
i=0
list1=[]
str=''
while(i<len(rhs_data)):
    str=str+ ' '+ rhs_data[i]
    esBigrams = ngrams(i, 2)
    #list1.append(list(esBigrams))
    i=i+1
word_fd = nltk.FreqDist(str)   #frequency distribution of each pair of letters or frequency of bigram appearing in dataset
bigram_fd = nltk.FreqDist(nltk.bigrams(str))

x=bigram_fd.most_common()

In [151]:
x


[(('o', 'm'), 2581),
 (('c', 'o'), 2530),
 (('.', 'c'), 2449),
 (('m', ' '), 2191),
 (('m', 'a'), 1743),
 (('a', 'i'), 1703),
 (('i', 'l'), 1536),
 ((' ', 'm'), 1517),
 (('e', '.'), 1372),
 (('l', '.'), 1241),
 (('.', 'e'), 1239),
 (('a', 'm'), 1230),
 (('l', 'e'), 1227),
 (('p', 'l'), 1203),
 (('m', 'p'), 1197),
 (('e', 'x'), 1179),
 (('x', 'a'), 1143),
 (('e', 'r'), 828),
 (('n', 'e'), 620),
 (('e', 't'), 572),
 (('h', 'o'), 549),
 (('o', 'r'), 544),
 (('.', 'n'), 515),
 (('i', 'n'), 514),
 (('t', ' '), 501),
 (('.', 'o'), 429),
 (('1', '.'), 428),
 (('r', 'g'), 421),
 (('g', ' '), 413),
 (('n', '.'), 394),
 (('o', '.'), 379),
 (('s', 'e'), 368),
 (('s', 't'), 364),
 (('a', 'l'), 351),
 (('v', 'e'), 341),
 (('c', 'a'), 325),
 (('t', '.'), 315),
 (('l', '1'), 314),
 (('a', 'r'), 288),
 (('o', 'o'), 265),
 (('r', '.'), 260),
 (('r', 'v'), 251),
 ((' ', 'c'), 248),
 (('s', '.'), 244),
 (('a', 'h'), 243),
 ((' ', 'y'), 239),
 (('y', 'a'), 239),
 (('a', 'n'), 232),
 (('o', 's'), 232),
 ((

In [70]:
df2 = pd.DataFrame(x, columns = ['Bigram', 'Frequency']) #The feature extracted is the bigram and its frequency in the dataset.

In [72]:
df2.to_csv('easy_ham_frquency.csv')

In [71]:
df2['Label']= 0

In [73]:
import pandas as pd

a = pd.read_csv('easy_ham_frquency.csv')
b = pd.read_csv('feature_extraction_bigram.csv')
b = b.dropna(axis=1)
merged = a.merge(b, on='Bigram')  #merge the frequency of bigram dataset of both phishing and non phishing.
merged.to_csv("output.csv", index=False)


In [7]:
raw_data = pd.read_csv("new_frquency.csv") 
x=raw_data['Bigram'][1]

In [20]:
def unicode(l):  #convert the bigram characters to unicode format so that it can be represented by classifiers.
    l=str(l)
    x=ord(l[2])
    return x

In [26]:
def unicode2(l): #Since there are 2 characters in bigram two times unicode conversion needs to be performed.
    l=str(l)
    x=ord(l[7])
    return x

In [21]:
raw_data['Bigram-1']=raw_data['Bigram'].apply(unicode)

In [27]:
raw_data['Bigram-2']=raw_data['Bigram'].apply(unicode2)

In [28]:
raw_data  #The features are unicode(Bigram-1) , unicode(Bigram-2), and their frequency.

Unnamed: 0      Bigram  Frequency  Label  Bigram-1  Bigram-2
0              0  ('o', 'r')       1037      0       111       114
1              1  ('r', 'g')        967      0       114       103
2              2  ('.', 'o')        947      0        46       111
3              3  ('m', 'a')        942      0       109        97
4              4  ('g', ' ')        873      0       103        32
5              5  ('l', '.')        849      0       108        46
6              6  ('a', '.')        790      0        97        46
7              7  ('.', 's')        779      0        46       115
8              8  ('l', 'a')        762      0       108        97
9              9  (' ', 'd')        722      0        32       100
10            10  ('a', 's')        713      0        97       115
11            11  ('s', 'l')        702      0       115       108
12            12  ('d', 'o')        697      0       100       111
13            13  ('.', 'c')        695      0        46        99
14            14  ('o', 'm')        682      0       111       109
15            15  ('o', 'g')        673      0       111       103
16            16  ('s', 'h')        662      0       115       104
17            17  ('u', 'l')        660      0       117       108
18            18  ('n', 'u')        659      0       110       117
19            19  ('h', 'n')        656      0       104       110
20            20  ('l', 'l')        652      0       108       108
21            21  ('g', 'm')        649      0       103       109
22            22  ('c', 'o')        640      0        99       111
23            23  ('m', ' ')        589      0       109        32
24            24  ('n', 'e')        486      0       110       101
25            25  ('e', 't')        457      0       101       116
26            26  ('t', ' ')        410      0       116        32
27            27  ('.', 'n')        406      0        46       110
28            28  ('e', '.')        301      0       101        46
29            29  ('s', '.')        295      0       115        46
...          ...         ...        ...    ...       ...       ...
2479        2479  ('f', 'b')          1      1       102        98
2480        2480  ('s', '7')          1      1       115        55
2481        2481  ('7', 't')          1      1        55       116
2482        2482  ('c', '8')          1      1        99        56
2483        2483  ('-', '6')          1      1        45        54
2484        2484  ('6', 'c')          1      1        54        99
2485        2485  ('1', 'e')          1      1        49       101
2486        2486  ('J', 'o')          1      1        74       111
2487        2487  ('T', 'h')          1      1        84       104
2488        2488  ('m', 'O')          1      1       109        79
2489        2489  ('O', '.')          1      1        79        46
2490        2490  ('X', 'A')          1      1        88        65
2491        2491  ('A', 'J')          1      1        65        74
2492        2492  ('J', 'E')          1      1        74        69
2493        2493  ('O', 'R')          1      1        79        82
2494        2494  ('G', ' ')          1      1        71        32
2495        2495  ('.', 'W')          1      1        46        87
2496        2496  ('W', 'o')          1      1        87       111
2497        2497  ('k', '-')          1      1       107        45
2498        2498  ('K', 'I')          1      1        75        73
2499        2499  ('M', 'B')          1      1        77        66
2500        2500  ('L', 'S')          1      1        76        83
2501        2501  ('j', 'q')          1      1       106       113
2502        2502  ('q', 's')          1      1       113       115
2503        2503  ('D', 'e')          1      1        68       101
2504        2504  ('p', 'S')          1      1       112        83
2505        2505  ('S', 'u')          1      1        83       117
2506        2506  ('F', 'R')          1      1       

In [29]:
raw_data.to_csv('new_frequency.csv')

In [35]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

raw_data = pd.read_csv("new_frequency.csv") 
features = ['Bigram-1','Bigram-2','Frequency']
X = raw_data[features]

y = raw_data.Label
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
clf = RandomForestClassifier(n_estimators=100,n_jobs=2,random_state=0)

# Train the Classifier to take the training features and learn how they relate
# to the training y (the species)
clf.fit(X, y)
pred=clf.predict(X_test)
print(pred[0:10])
proba=clf.predict_proba(X_test)[0:10]
print(proba)
y_test1=y_test.as_matrix()
results = confusion_matrix(y_test1, pred) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :',accuracy_score(y_test1, pred))
print ('Report : ')
print(classification_report(y_test1, pred))


[1 0 1 0 0 1 1 1 1 1]
[[0.     1.    ]
 [0.81   0.19  ]
 [0.07   0.93  ]
 [0.77   0.23  ]
 [0.81   0.19  ]
 [0.08   0.92  ]
 [0.4245 0.5755]
 [0.13   0.87  ]
 [0.19   0.81  ]
 [0.     1.    ]]
Confusion Matrix :
[[223  14]
 [  2 514]]
Accuracy Score : 0.9787516600265604
Report : 
             precision    recall  f1-score   support

          0       0.99      0.94      0.97       237
          1       0.97      1.00      0.98       516

avg / total       0.98      0.98      0.98       753



C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


In [38]:
import pickle
filename = 'msgid.sav'
pickle.dump(clf, open(filename, 'wb'))

Testing with a sample input

In [158]:
str1 = '200503200335.j2K3ZmR06695@spam.thegeekempire.net'
str2=str1.replace('>','')
x=str2.split('@')

y=x[1]
print(y)

spam.thegeekempire.net


In [159]:
import nltk
from nltk.util import ngrams
from nltk.collocations import BigramCollocationFinder
from nltk.metrics import BigramAssocMeasures
import re, string, collections
from nltk.util import ngrams # function for making ngrams

esBigrams = ngrams(y, 2)
    

word_fd = nltk.FreqDist(y)
bigram_fd = nltk.FreqDist(nltk.bigrams(y))

x=bigram_fd.most_common()

In [160]:
x

[(('s', 'p'), 1),
 (('p', 'a'), 1),
 (('a', 'm'), 1),
 (('m', '.'), 1),
 (('.', 't'), 1),
 (('t', 'h'), 1),
 (('h', 'e'), 1),
 (('e', 'g'), 1),
 (('g', 'e'), 1),
 (('e', 'e'), 1),
 (('e', 'k'), 1),
 (('k', 'e'), 1),
 (('e', 'm'), 1),
 (('m', 'p'), 1),
 (('p', 'i'), 1),
 (('i', 'r'), 1),
 (('r', 'e'), 1),
 (('e', '.'), 1),
 (('.', 'n'), 1),
 (('n', 'e'), 1),
 (('e', 't'), 1)]

In [161]:
df = pd.DataFrame(x, columns = ['Bigram', 'Frequency']) 

In [162]:
df

Bigram  Frequency
0   (s, p)          1
1   (p, a)          1
2   (a, m)          1
3   (m, .)          1
4   (., t)          1
5   (t, h)          1
6   (h, e)          1
7   (e, g)          1
8   (g, e)          1
9   (e, e)          1
10  (e, k)          1
11  (k, e)          1
12  (e, m)          1
13  (m, p)          1
14  (p, i)          1
15  (i, r)          1
16  (r, e)          1
17  (e, .)          1
18  (., n)          1
19  (n, e)          1
20  (e, t)          1

In [163]:
def unicode1(l):
    l=str(l)
    x=ord(l[2])
    return x

In [164]:
def unicode2(l):
    l=str(l)
    x=ord(l[7])
    return x

In [165]:
df['Bigram-1']=raw_data['Bigram'].apply(unicode1)

In [166]:
df['Bigram-2']=raw_data['Bigram'].apply(unicode2)

In [167]:
df

Bigram  Frequency  Bigram-1  Bigram-2
0   (s, p)          1       111       114
1   (p, a)          1       114       103
2   (a, m)          1        46       111
3   (m, .)          1       109        97
4   (., t)          1       103        32
5   (t, h)          1       108        46
6   (h, e)          1        97        46
7   (e, g)          1        46       115
8   (g, e)          1       108        97
9   (e, e)          1        32       100
10  (e, k)          1        97       115
11  (k, e)          1       115       108
12  (e, m)          1       100       111
13  (m, p)          1        46        99
14  (p, i)          1       111       109
15  (i, r)          1       111       103
16  (r, e)          1       115       104
17  (e, .)          1       117       108
18  (., n)          1       110       117
19  (n, e)          1       104       110
20  (e, t)          1       108       108

In [168]:
features = ['Bigram-1','Bigram-2','Frequency']
X = df[features]
pred=clf.predict(X) #For each pair it predicts if phis or not phish.
print(pred)
proba=clf.predict_proba(X_test)[0:10]
print(proba)

[0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 0 0 1 0 1 1]
[[0.     1.    ]
 [0.81   0.19  ]
 [0.07   0.93  ]
 [0.77   0.23  ]
 [0.81   0.19  ]
 [0.08   0.92  ]
 [0.4245 0.5755]
 [0.13   0.87  ]
 [0.19   0.81  ]
 [0.     1.    ]]


In [169]:
count1=0
count0=0
for i in range(len(pred)):
    if(pred[i] == 1):
       count1=count1+1
    else:
       count0=count0+1
if(count1>count0):
   print('Phishing')
elif(count1<count0):
   print('Non-Phishing')
else:
   print('phishing')

Non-Phishing
