After preprocessing the message ids are stored in two files 'easyham.csv'(non phishing message id) and 'phishing.csv'

In [10]:
import numpy as np
import pandas as pd
df=pd.read_csv('easy_ham.csv')
rhs_data=df['RHS']

In [11]:
import nltk
from nltk.util import ngrams
from nltk.collocations import BigramCollocationFinder
from nltk.metrics import BigramAssocMeasures
import re, string, collections
from nltk.util import ngrams # function for making ngrams
i=0
list1=[]
str=''
while(i<len(rhs_data)):
    str=str+ ' '+ rhs_data[i]
    esBigrams = ngrams(i, 2)
    #list1.append(list(esBigrams))
    i=i+1
word_fd = nltk.FreqDist(str)   #frequency distribution of each pair of letters or frequency of bigram appearing in dataset
bigram_fd = nltk.FreqDist(nltk.bigrams(str))

x=bigram_fd.most_common()

In [13]:
x[0:5]


[(('o', 'r'), 1037),
 (('r', 'g'), 967),
 (('.', 'o'), 947),
 (('m', 'a'), 942),
 (('g', ' '), 873)]

In [70]:
df2 = pd.DataFrame(x, columns = ['Bigram', 'Frequency']) #The feature extracted is the bigram and its frequency in the dataset.

In [72]:
df2.to_csv('easy_ham_frquency.csv')

In [71]:
df2['Label']= 0

In [73]:
import pandas as pd

a = pd.read_csv('easy_ham_frquency.csv')
b = pd.read_csv('feature_extraction_bigram.csv')
b = b.dropna(axis=1)
merged = a.merge(b, on='Bigram')  #merge the frequency of bigram dataset of both phishing and non phishing.
merged.to_csv("output.csv", index=False)


In [27]:
raw_data = pd.read_csv("new_frquency.csv") 
x=raw_data['Bigram']

In [32]:
def unicode(l):  #convert the bigram characters to unicode format so that it can be represented by classifiers.
    #l=str(l)
    x=ord(l[2])
    return x

In [33]:
def unicode2(l): #Since there are 2 characters in bigram two times unicode conversion needs to be performed.
    #l=str(l)
    x=ord(l[7])
    return x

In [34]:
raw_data['Bigram-1']=raw_data['Bigram'].apply(unicode)

In [35]:
raw_data['Bigram-2']=raw_data['Bigram'].apply(unicode2)

In [36]:
raw_data[0:5]  #The features are unicode(Bigram-1) , unicode(Bigram-2), and their frequency.

Unnamed: 0      Bigram  Frequency  Label  Bigram-1  Bigram-2
0           0  ('o', 'r')       1037      0       111       114
1           1  ('r', 'g')        967      0       114       103
2           2  ('.', 'o')        947      0        46       111
3           3  ('m', 'a')        942      0       109        97
4           4  ('g', ' ')        873      0       103        32

In [29]:
raw_data.to_csv('new_frequency.csv')

In [35]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

raw_data = pd.read_csv("new_frequency.csv") 
features = ['Bigram-1','Bigram-2','Frequency']
X = raw_data[features]

y = raw_data.Label
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
clf = RandomForestClassifier(n_estimators=100,n_jobs=2,random_state=0)

# Train the Classifier to take the training features and learn how they relate
# to the training y (the species)
clf.fit(X, y)
pred=clf.predict(X_test)
print(pred[0:10])
proba=clf.predict_proba(X_test)[0:10]
print(proba)
y_test1=y_test.as_matrix()
results = confusion_matrix(y_test1, pred) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :',accuracy_score(y_test1, pred))
print ('Report : ')
print(classification_report(y_test1, pred))


[1 0 1 0 0 1 1 1 1 1]
[[0.     1.    ]
 [0.81   0.19  ]
 [0.07   0.93  ]
 [0.77   0.23  ]
 [0.81   0.19  ]
 [0.08   0.92  ]
 [0.4245 0.5755]
 [0.13   0.87  ]
 [0.19   0.81  ]
 [0.     1.    ]]
Confusion Matrix :
[[223  14]
 [  2 514]]
Accuracy Score : 0.9787516600265604
Report : 
             precision    recall  f1-score   support

          0       0.99      0.94      0.97       237
          1       0.97      1.00      0.98       516

avg / total       0.98      0.98      0.98       753



C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


In [38]:
import pickle
filename = 'msgid.sav'
pickle.dump(clf, open(filename, 'wb'))

Testing with a sample input

In [37]:
str1 = '200503200335.j2K3ZmR06695@spam.thegeekempire.net'
str2=str1.replace('>','')
x=str2.split('@')

y=x[1]
print(y)

spam.thegeekempire.net


In [38]:
import nltk
from nltk.util import ngrams
from nltk.collocations import BigramCollocationFinder
from nltk.metrics import BigramAssocMeasures
import re, string, collections
from nltk.util import ngrams # function for making ngrams

esBigrams = ngrams(y, 2)
    

word_fd = nltk.FreqDist(y)
bigram_fd = nltk.FreqDist(nltk.bigrams(y))

x=bigram_fd.most_common()

In [39]:
x[0:5]

[(('s', 'p'), 1),
 (('p', 'a'), 1),
 (('a', 'm'), 1),
 (('m', '.'), 1),
 (('.', 't'), 1)]

In [40]:
df = pd.DataFrame(x, columns = ['Bigram', 'Frequency']) 

In [44]:
def unicode1(l):
    #l=str(l)
    x=ord(l[2])
    return x

In [45]:
def unicode2(l):
    #l=str(l)
    x=ord(l[7])
    return x

In [46]:
df['Bigram-1']=raw_data['Bigram'].apply(unicode1)

In [47]:
df['Bigram-2']=raw_data['Bigram'].apply(unicode2)

In [48]:
df[0:5]

Bigram  Frequency  Bigram-1  Bigram-2
0  (s, p)          1       111       114
1  (p, a)          1       114       103
2  (a, m)          1        46       111
3  (m, .)          1       109        97
4  (., t)          1       103        32

In [168]:
features = ['Bigram-1','Bigram-2','Frequency']
X = df[features]
pred=clf.predict(X) #For each pair it predicts if phis or not phish.
print(pred)
proba=clf.predict_proba(X_test)[0:10]
print(proba)

[0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 0 0 1 0 1 1]
[[0.     1.    ]
 [0.81   0.19  ]
 [0.07   0.93  ]
 [0.77   0.23  ]
 [0.81   0.19  ]
 [0.08   0.92  ]
 [0.4245 0.5755]
 [0.13   0.87  ]
 [0.19   0.81  ]
 [0.     1.    ]]


In [169]:
count1=0
count0=0
for i in range(len(pred)):
    if(pred[i] == 1):
       count1=count1+1
    else:
       count0=count0+1
if(count1>count0):
   print('Phishing')
elif(count1<count0):
   print('Non-Phishing')
else:
   print('phishing')

Non-Phishing
